theme: jekyll-theme-architect
title: Welcome to the Jennie's homepage!
description: I want to use this page to record my coding progress. Feel free to bookmark this to keep an eye on my projects updtes.
